export const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "1234567890",
    country: "United States",
    message: "Hello, how are you?",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phone: "0987654321",
    country: "Canada",
    message: "Hello, how are you?",
  },
  {
    id: 3,
    name: "Jim Doe",
    email: "jim.doe@example.com",
    phone: "1111111111",
    country: "United Kingdom",
    message: "Hello, how are you?",
  },
  {
    id: 4,
    name: "Jill Doe",
    email: "jill.doe@example.com",
    phone: "2222222222",
    country: "Australia",
    message: "Hello, how are you?",
  },
  {
    id: 5,
    name: "Jack Doe",
    email: "jack.doe@example.com",
    phone: "3333333333",
    country: "New Zealand",
    message: "Hello, how are you?",
  },
  {
    id: 6,
    name: "Jill Doe",
    email: "jill.doe@example.com",
    phone: "2222222222",
    country: "Australia",
    message: "Hello, how are you?",
  },
  {
    id: 7,
    name: "Jill Doe",
    email: "jill.doe@example.com",
    phone: "2222222222",
    country: "Australia",
    message: "Hello, how are you?",
  },
  {
    id: 8,
    name: "Jill Doe",
    email: "jill.doe@example.com",
    phone: "2222222222",
    country: "Australia",
    message: "Hello, how are you?",
  },
  {
    id: 10,
    name: "Jill Doe",
    email: "jill.doe@example.com",
    phone: "2222222222",
    country: "Australia",
    message: "Hello, how are you?",
  },
];